### PR TITLE
Use channel instead of sync.Once

### LINKED ISSUE #35: goroutine leak with sync.Once in transport.go
sync.Once is basically a lock and a bool that runs the given function synchronously. So all but the first call to transport.Run() blocks until t.run() finishes. This causes a goroutine leak for clients, since each Client.Call does `go c.xp.Run()`.

### PR DESCRIPTION
**Pull request by akalin-keybase**
This fixes a goroutine leak.

This will close #35.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
@maxtaco not urgent, feel free to look in the morning.

**Comment by maxtaco** [comment]
Very cool, thanks Fred!  :+1:

**Comment by akalin-keybase** [comment]
cc @jzila

**Comment by jzila** [comment]
I'll follow up in the morning. I don't love telling the transport whether to run in a goroutine or not; it seems like a leaky abstraction to me.

Why not take the `startCh` solution in lieu of the `sync.Once` and leave the goroutines upstream instead of passing down the `bg` parameter?

**Comment by akalin-keybase** [comment]
It needlessly creates a goroutine for every RPC call. Goroutines are cheap, but we shouldn't go crazy with them.

I can probably pull the bool out of the transport method, but there'll still be a function that takes a bool that spawns a goroutine or not based on that bool.

**Comment by jzila** [comment]
In that case I'd rather have a `RunAsync` method that separates out that functionality.

**Comment by akalin-keybase** [comment]
Okay, done. PTAL!

**Comment by jzila** [comment]
LGTM after `Server` feedback.

**Pull request closed without merging**
