### PR TITLE
Vendor dependencies using govendor

### PR DESCRIPTION
**Pull request by jacobhaven**
r? @maxtaco @jzila @akalin-keybase

### CODE REVIEW

**Comment by jzila** [comment]
We switched from ugorji/codec?

**Comment by jacobhaven** [comment]
@jzila you approved that PR :P #69

**Comment by jzila** [comment]
Yeah for some reason I thought we'd switched back. Anyway, :+1:

**Comment by jacobhaven** [comment]
It's been decided that we should only vendor at top-level projects to avoid conflicts between versions vendored by different libraries.

This does mean that all top level projects need to vendor all the dependencies of all their dependencies (and know that the versions chosen will work for all of them). Go package management is still a bit of a mess.

**Pull request closed without merging**
