### PR TITLE
Use newCanceledError in request.go

### LINKED ISSUE #29: callRequest.Reply should use newCanceledError
It should also use log.Info instead of log.Warning.

### PR DESCRIPTION
**Pull request by akalin-keybase**
Also add log.Info. This will close #29.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
cc @jzila

**Comment by jzila** [comment]
This conflicts with changes in https://github.com/keybase/go-framed-msgpack-rpc/pull/34. I've added the remaining differences to that PR.

Since this PR isn't a critical fix, we shouldn't be pre-empting the `devel` branch, since each time that's done, more conflicts are introduced that need to be resolved against existing PRs.

**Comment by akalin-keybase** [comment]
Okay, I can move this to the devel branch. I wanted to get this in for better debugging before the demo, but since that's gone this isn't critical.

**Comment by jzila** [comment]
@akalin-keybase I already have a PR with all this code on the devel branch.

**Comment by akalin-keybase** [comment]
Okay, but I kinda want to get this in before that PR -- there's no reason to tie it to that one.

**Comment by jzila** [comment]
What's blocking that PR?

**Comment by akalin-keybase** [comment]
I'll have to review it again, and will probably have more comments, ask for more tests, etc.

**Comment by jzila** [comment]
Up to you. I'd rather avoid the conflict, but if you feel that this is important enough I understand.

**Comment by akalin-keybase** [comment]
Rebasing should intelligently remove the duplicate commit in your branch, I think.

**Comment by jzila** [comment]
I did the `Info` stuff separate from this fix, so it'll definitely conflict twice. But that's the cost of doing business, I guess.

**Comment by akalin-keybase** [comment]
I'll merge this now.

**Comment by akalin-keybase** [comment]
(into both devel and master)

**Pull request closed without merging**
