### PR TITLE
fix missing wef

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by maxtaco** [comment]
Can @strib  or @jzila give this one a second set of eyes?

**Comment by jzila** [comment]
How was anything working without this?

**Comment by jzila** [comment]
Ah probably because we mostly use a standard `wef`

**Comment by songgao** [comment]
Probably because we are only using `NewConnectionWithTransport` in KBFS and as @strib said we were not returning any error from KBFS RPC handler yet

**Comment by maxtaco** [comment]
I don't think KBFS has ever acted as an RPC server before, and I think gregor used a different code path.  @mmaxim  is that correct?

**Comment by jzila** [comment]
OK Please test this vendored into {gregor, client, kbfs, kbfs-server}

**Comment by maxtaco** [comment]
yeah the standard wef will break the connection if the other side is using a special wef

**Comment by jzila** [comment]
So KBFS will start acting as an RPC server?

**Comment by maxtaco** [comment]
Need to do so for chat...

**Comment by jzila** [comment]
ok go for it

**Comment by songgao** [comment]
All four tests passed:

https://github.com/keybase/gregor/pull/152
https://github.com/keybase/kbfs-server/pull/90
https://github.com/keybase/client/pull/3790
https://github.com/keybase/kbfs/pull/223

Merging!

**Pull request merged**
