### PR TITLE
Put seqid in taskEndCh

### PR DESCRIPTION
**Pull request by patrickxb**
Fix for #88

### CODE REVIEW

**Comment by jzila** [comment]
:+1: 
If you want to trigger the `cancelFunc` for successes as well, that should be fine. But I don't think it's necessary.

**Comment by jzila** [comment]
My bad, this actually needs to go into `handleReceiveDispatch`

**Comment by patrickxb** [comment]
Thanks to @jzila I think we figured this out...

**Comment by jzila** [comment]
Looks good, thanks Patrick for doing all this awesome investigation!

**Pull request merged**
