### PR TITLE
Wrap errors even if the protocol or method isn't found

### PR DESCRIPTION
**Pull request by jzila**

### CODE REVIEW

**Comment by maxtaco** [comment]
need some work (has the previous fix in it), but in general, we need this!

**Comment by jzila** [comment]
@maxtaco that's not the previous fix, I added the fix to `Notify` as well.

**Comment by maxtaco** [comment]
got it!

ok, no urgency, we can restart 1.0.8, 1.0.9-0 and 1.0.9-1 with 1.0.10!!

**Comment by jzila** [comment]
@akalin-keybase gave his "LGTM" in Slack

**Pull request merged**
