### PR TITLE
standard log option format

### PR DESCRIPTION
**Pull request by mmaxim**
These log options get used in a couple different places now, I think we should just promote to this package. @maxtaco thoughts?

### CODE REVIEW

**Comment by maxtaco** [comment]
:+1:

**Comment by jzila** [comment]
Could I see an example of where this comes from?

**Comment by mmaxim** [comment]
https://github.com/keybase/gregor/blob/CORE-2960/bin/gregord/main.go#L21-L27 is the only use-case so far, although the goal would be to have this code: https://github.com/keybase/client/blob/master/go/libkb/rpc_log.go use it as well.

**Comment by jzila** [comment]
Thanks Mike! I don't really love that the options are all part of a string,
it would seem to make more sense to pass in a struct or bitfield. I'd also
prefer the comparators to be constants. That said, I wouldn't block
anything on making those changes.

**Comment by mmaxim** [comment]
Yeah I see your point. One easy way out here might be to just rename this function like `Parse`, which would make it more acceptable to have a string coming in. What do you think?

**Comment by jzila** [comment]
Sgtm

**Comment by maxtaco** [comment]
Meant for parsing command line opts!

**Comment by jzila** [comment]
I'm not sure RPC should be parsing opts since that prescribes how it will
be used.

**Comment by maxtaco** [comment]
But this code is common to two libraries that both use the rpc library. In
that sense it is like connection.go

We're it not for this refactor we need to copy paste the code or introduce
another shared module.

**Comment by jzila** [comment]
👍

**Pull request merged**
