### PR TITLE
GetCloseBroadcaster is a buffered, broadcast channel of when the transport closes

### PR DESCRIPTION
**Pull request by maxtaco**
- is easier to use than AddCloseListener

### CODE REVIEW

**Comment by maxtaco** [comment]
@jzila / @akalin-keybase , what do you think?

**Comment by akalin-keybase** [comment]
I'm not wild about having two slightly different ways of doing the same thing.

I looked over the existing uses of AddCloseListener (2, other than Gregor), and they both add the close listener before calling srv.Run(), which seems to be an implicit assumption in how AddCloseListener is intended to be used. Maybe AddCloseListener should abort if it's used after srv.Run() is called. It should be documented, at least.

My suggestion is to create a buffered channel when creating the connection in gregor/connection.go, pass it to AddCloseListener before calling startRPCServer(), and plumb it through newConnectionCh to wherever you want it to go.

The ideal solution would be to implement the Run() vs RunAsync() split, and then have RunAsync() return an `error chan` that's sent to when the connection closed. We don't actually use more than one listener per connection as far as I can tell, and the client can multiplex itself if it wants to.

We might not even need RunAsync() at all -- if the client wants to run the server asynchronously, it can simply spawn a goroutine to call Run(). I vaguely remember trying to do this before, but I don't remember why I ended up not doing it.

**Comment by maxtaco** [comment]
Agreed it doesn't make send to do the same thing two different ways. But if we had to have one or the other it seems as if you prefer something like what I've proposed over AddCloseListener?

**Comment by maxtaco** [comment]
(None of this is too important for our use case btw.  There are several workarounds)

**Comment by jzila** [comment]
I'm inclined to agree with both of you: on the one hand I'd rather not have two ways of representing the same functionality. On the other, this method is definitely better than `AddCloseListener`.

**Comment by maxtaco** [comment]
Do we really need the error?

**Comment by jzila** [comment]
Looks like it's used in [service/main.go](https://github.com/keybase/client/blob/474eaf09dc279c595b0dd41b8b63ed72b1683223/go/service/main.go#L94), where it [doesn't require the error](https://github.com/keybase/client/blob/474eaf09dc279c595b0dd41b8b63ed72b1683223/go/libkb/connmgr.go#L67), and [kex2/provisionee.go](https://github.com/keybase/client/blob/474eaf09dc279c595b0dd41b8b63ed72b1683223/go/kex2/provisionee.go#L103), [where it does require the error](https://github.com/keybase/client/blob/474eaf09dc279c595b0dd41b8b63ed72b1683223/go/kex2/provisionee.go#L87).

**Comment by akalin-keybase** [comment]
Yeah, it's the error that's the sticking point. Otherwise, I'd prefer `GetCloseBroadcaster()`. Or have `GetCloseBroadcaster()` return a channel that returns an error, and handle that internally.

**Comment by akalin-keybase** [comment]
I think this PR's been superseded!

**Pull request closed without merging**
